taskmanager/main/urls.py
from django.urls import path
from . import views
from .views import RegisterUser, LoginUser, LogoutUser,ChangeUser

urlpatterns = [
    path('analytics',views.testable,name = 'analytics'),
    path('login',LoginUser.as_view(), name = 'login'), 
    path('registration',RegisterUser.as_view(),name = 'registration'),
    path('logout',LogoutUser,name = 'logout'),
    path('base',views.base),
    path('test',views.test),
    path('dashboard',views.AddProject,name = 'dashboard'),
    path('users', views.ChangeUserF,name = 'users'),
    path('settings', views.settings),
    path('',views.redirectlogin)


]

taskmanager/taskmanager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

taskmanager/main/models.py
from django.db import models
from django.contrib.auth.models import User



class UserData(models.Model):
    Usernick = models.CharField(primary_key=True, max_length=20,default='ERROR')
    UserF = models.ForeignKey(User, on_delete=models.CASCADE)
    Fullname = models.CharField(max_length=20, null = True)
    UserAvatar = models.ImageField(upload_to='./static/DbImages/DBimages',null=True,default='./static/DbImages/DBimages/userunknown.jpg')
    UserGitLink = models.CharField(max_length=50, null = True)
    UserGroup = models.CharField(max_length=15, null = True)

class Projects(models.Model):
    Usernick = models.ForeignKey(UserData, on_delete=models.CASCADE)
    ProjectName = models.CharField(max_length=100)
    ProjectDescription = models.TextField(null = True, blank = True,)
    ProjectLink = models.URLField(max_length=100)
    ProjectDate = models.DateTimeField(auto_now_add=True)

taskmanager/main/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import UserData, Projects
from django.shortcuts import render




class UserForm(UserCreationForm):
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Confirm password'}))
    class Meta:
        model = User
        fields = ('email','password1','password2','username')
        widgets = {
            "email": forms.TextInput(attrs={'placeholder': 'Email'}),
            "username": forms.TextInput(attrs={'placeholder': "Username"}),
        }


class UserLoginForm(AuthenticationForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    class Meta:
        model = User
        fields = ('username','password')
        widgets = {
            "username": forms.TextInput(attrs={'placeholder': "Username"}),
        }

def get_id(request):
    value = request.user.id
    return value
class UserChangeForm(forms.ModelForm):


    class Meta:
        model = UserData
        fields = ('Fullname','UserGitLink','UserGroup','UserAvatar')

        widgets = {
            'Fullname': forms.TextInput(attrs={'placeholder': "Fullname"}),
            'UserGitLink': forms.TextInput(attrs={'placeholder': "Git-Hub Link"}),
            'UserGroup': forms.TextInput(attrs={'placeholder': "Group"}),

        }

class CreateProjectForm(forms.ModelForm):
    class Meta:
        model = Projects
        fields = ('ProjectName', 'ProjectDescription','ProjectLink')
        widgets = {
            "ProjectName": forms.TextInput(attrs={'placeholder': 'Project name'}),
            "ProjectDescription": forms.TextInput(attrs={'placeholder': "Description"}),
            "ProjectLink": forms.URLInput(attrs={'placeholder':'GitHub project link'})
        }

taskmanager/main/views.py
from django.contrib.auth import logout
from django.contrib.auth.views import LoginView
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from.forms import *
from django.contrib.auth.mixins import  LoginRequiredMixin
from django.views.generic import CreateView
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .functions import *
from .tests import *


def analytics(request):
    return render(request, 'main/analytics.html')

def dashboard(request):
    return render(request,'main/dashboard.html')

def users(request):
    return render(request,'main/users.html')

def settings(request):
    return render(request,'main/settings.html')



def base(request):
    return render(request,'main/base.html')

def test(requset):
    return render(requset,'main/test.html')

def create(request):
    return render(request, 'main/create.html')

def login(request):
    return  render(request,'main/login.html')

class RegisterUser(CreateView):
    form_class = UserForm
    template_name = 'main/register.html'
    success_url = reverse_lazy('login')

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #
    #     print(context.items())
    #     return dict(list(context.items()))

class LoginUser(LoginView):
    form_class = UserLoginForm
    template_name = 'main/login.html'

def LogoutUser(request):
    logout(request)
    return redirect('login')

class ChangeUser(CreateView):
    form_class = UserChangeForm
    template_name = 'main/users.html'


def ChangeUserF(request):
    if request.method == 'POST':
        form = UserChangeForm(request.POST)

        if form.is_valid():
            cldata = form.cleaned_data
            try:
                print(cldata['UserAvatar'])
                data = UserData()
                data.UserF = User.objects.get(id=request.user.id)

                data.UserGroup = cldata['UserGroup']
                data.UserGitLink = cldata['UserGitLink']
                data.Fullname = cldata['Fullname']
                data.Usernick = request.user.username
                data.save()
            except:
                print(cldata['UserAvatar'])
                my_model = get_object_or_404(UserData, pk=request.user.username)
                form = UserChangeForm(request.POST, instance=my_model)

                data = form
                data.UserF = User.objects.get(id=request.user.id)
                data.UserGroup = cldata['UserGroup']
                data.UserGitLink = cldata['UserGitLink']
                data.Fullname = cldata['Fullname']
                data.UserAvatar = request.FILES['UserAvatar']
                data.save()
            return redirect('users')
    else:
        try:
            userdata = UserData.objects.get(pk=request.user.username)
        except:
            userdata = 0

        form = UserChangeForm(request.POST)
        try:
            form.fields['UserGroup'].widget.attrs['value'] = userdata.UserGroup
            form.fields['UserGitLink'].widget.attrs['value'] = userdata.UserGitLink
            form.fields['Fullname'].widget.attrs['value'] = userdata.Fullname
            form.fields['UserAvatar'].widget.attrs['value'] = userdata.UserAvatar

        except:
            pass
        data = 0

    return render(request, 'main/users.html', {'form': form, 'data': data,'userdata' : userdata })


def AddProject(request):
    form = CreateProjectForm(request.POST)
    if request.method == 'POST':
        form = CreateProjectForm(request.POST)

        if form.is_valid():
            data = form.cleaned_data

            project = Projects()
            project.Usernick = UserData.objects.get(pk = request.user.username)
            project.ProjectName = data['ProjectName']
            project.ProjectDescription = data['ProjectDescription']
            project.ProjectLink = data['ProjectLink']
            project.save()
            return redirect('analytics')
    return render(request,'main/dashboard.html',{'form':form})

def testable(request):
    projects = Projects.objects.all()
    userdata = UserData.objects

    return render(request, 'main/analytics.html',{'projects': projects, 'userdata': userdata})

def redirectlogin(request):

    return redirect('login')

taskmanager/main/templates/main/analytics.html
{% extends 'main/base.html' %}
{% load static %}

{% block main %}
    <h1>Analytics</h1>
            <!-- Analyses -->
            <div class="analyse">
                <div class="sales">
                    <div class="status">
                        <div class="info">
                            <h3>Green Scale</h3>
                            <h1>{Values_1}</h1>
                        </div>
                        <div class="progresss">
                            <svg>
                                <circle cx="38" cy="38" r="36"></circle>
                            </svg>
                            <div class="percentage">
                                <p>+81%</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="visits">
                    <div class="status">
                        <div class="info">
                            <h3>Red Scale</h3>
                            <h1>{Values_2}</h1>
                        </div>
                        <div class="progresss">
                            <svg>
                                <circle cx="38" cy="38" r="36"></circle>
                            </svg>
                            <div class="percentage">
                                <p>-48%</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="searches">
                    <div class="status">
                        <div class="info">
                            <h3>Blue Scale</h3>
                            <h1>{Value_3}</h1>
                        </div>
                        <div class="progresss">
                            <svg>
                                <circle cx="38" cy="38" r="36"></circle>
                            </svg>
                            <div class="percentage">
                                <p>+21%</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="recent-orders">
                <h2>Data Base</h2>
                <table>
                    <thead>
                        <tr>
                            <th>ProjectName</th>
                            <th>Link</th>
                            <th>Name</th>
                            <th>Date</th>
                            <th>Group</th>
                        </tr>

                    </thead>
                    <tbody>
                    {% for project in projects%}
                    <tr>
                    <td>
                        {{ project.ProjectName }}
                    </td>
                        <td>
                            <a href = '{{project.ProjectLink}}'>{{project.ProjectLink}}</a>
                        </td>
                    <td>
                        {{project.Usernick.Fullname}}
                    </td>
                    <td>
                        {{project.ProjectDate}}
                    </td>
                    <td>
                        {{project.Usernick.UserGroup}}
                    </td>
                        {% endfor %}
                    </tbody>
                </table>
                <a href="#">Show All</a>
            </div>
{% endblock %}

taskmanager/main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Sharp" rel="stylesheet">
    <link rel="stylesheet" href="{%static 'css/css5/style.css'%}">
    <title>Django DataBase</title>
</head>

<body>
    <div class="container">
{% block sidebar %}
<aside>
            <div class="toggle">
                <div class="logo">
                    <img src="{%static 'images/DB Logo.png'%}">
                    <h2>Django<span class="danger">DB</span></h2>
                </div>
                <div class="close" id="close-btn">
                    <span class="material-icons-sharp">
                        close
                    </span>
                </div>
            </div>

            <div class="sidebar">
                {% if request.path == '/dashboard' %}
                <a href="dashboard" class="activedashboard">
                    <span class="material-icons-sharp">
                        dashboard
                    </span>
                    <h3>Dashboard</h3>
                </a>
                {% else %}
                <a href="dashboard">
                    <span class="material-icons-sharp">
                        dashboard
                    </span>
                    <h3>Dashboard</h3>
                </a>
                {% endif %}
                {% if request.path == '/users' %}
                <a href="users" class="active">
                    <span class="material-icons-sharp">
                        person_outline
                    </span>
                    <h3>Profile</h3>
                </a>
                {% else %}
                <a href="users">
                    <span class="material-icons-sharp">
                        person_outline
                    </span>
                    <h3>Profile</h3>
                </a>
                {% endif %}
                {% if request.path == '/analytics' %}
                <a href="analytics" class="active">
                    <span class="material-icons-sharp">
                        insights
                    </span>
                    <h3>Analytics</h3>
                </a>
                {% else %}
                <a href="analytics">
                    <span class="material-icons-sharp">
                        insights
                    </span>
                    <h3>Analytics</h3>
                </a>
                {% endif %}
                {% if request.path == '/settings' %}
                <a href="settings" class="active">
                    <span class="material-icons-sharp">
                        settings
                    </span>
                    <h3>Settings</h3>
                </a>
                {% else %}
                <a href="settings">
                    <span class="material-icons-sharp">
                        settings
                    </span>
                    <h3>Settings</h3>
                </a>
                {% endif %}
                <a href="{%url 'logout'%}">
                    <span class="material-icons-sharp">
                        logout
                    </span>
                    <h3>Logout</h3>
                </a>
            </div>
        </aside>
{% endblock %}
<main>
{% block main %}
    <h1>
    {%block title%}
    Main Block
    {%endblock%}
    </h1>

{% endblock %}
    </main>
        {% block rightsection %}
        <div class="right-section">
            <div class="nav">
                <button id="menu-btn">
                    <span class="material-icons-sharp">
                        menu
                    </span>
                </button>
                <div class="dark-mode">
                    <span class="material-icons-sharp active">
                        light_mode
                    </span>
                    <span class="material-icons-sharp">
                        dark_mode
                    </span>
                </div>
                {% if request.user.is_authenticated %}
                <div class="profile">
                    <div class="info">
                        <p>Hey, <b>{{user.username}}</b></p>
                        {% if user.username == "admin" %}
                        <small class="text-muted">Admin</small>
                        {% else %}
                        <small class="text-muted">User</small>
                        {%endif%}
                    </div>
                    <div class="profile-photo">
                        <img src="images/profile-1.jpg">
                    </div>
                </div>
                {% else %}
                <a class="loginbtn" href="login">Login</a>
                <a class="createacc" href="registration">Create account</a>

            {%endif%}

            </div>
            {% block rightuser %}
            <div class="user-profile">
                <div class="logo">
                    <img src="{%static 'images/DB Logo.png'%}">
                    <h2>{GitHubName}</h2>
                    <p>{GitHubDesc}</p>
                </div>
            </div>

            <div class="reminders">
                <div class="header">
                    <h2>GitUpdates</h2>
                    <span class="material-icons-sharp">
                        notifications_none
                    </span>
                </div>

                <div class="notification">
                    <div class="icon">
                        <span class="material-icons-sharp">
                            volume_up
                        </span>
                    </div>
                    <div class="content">
                        <div class="info">
                            <h3>Update_1</h3>
                            <small class="text_muted">
                                {update_time}
                            </small>
                        </div>
                        <span class="material-icons-sharp">
                            more_vert
                        </span>
                    </div>
                </div>

                <div class="notification deactive">
                    <div class="icon">
                        <span class="material-icons-sharp">
                            edit
                        </span>
                    </div>
                    <div class="content">
                        <div class="info">
                            <h3>Update_2</h3>
                            <small class="text_muted">
                                {update_time}
                            </small>
                        </div>
                        <span class="material-icons-sharp">
                            more_vert
                        </span>
                    </div>
                </div>

                <div class="notification add-reminder">
                    <div>
                        <span class="material-icons-sharp">
                            add
                        </span>
                        <h3>Add Reminder</h3>
                    </div>
                </div>
            </div>
            {% endblock %}
        </div>
        {% endblock %}
        </div>
    {% block jscripts %}
    <script src="{%static 'JavaScript/index.js'%}"></script>
    <script src="{%static 'JavaScript/orders.js'%}"></script>
    {% endblock %}
</body>
</html>

taskmanager/main/templates/main/dashboard.html
{% extends 'main/base.html' %}
{% load static %}

{% block main %}
<h1>Dashboard</h1>
            <div class="analyse">
                <div class="AddProject">
                    <h2>Add project</h2>
                    <form class="login-form" method="post">

            {% csrf_token %}
            {{form.ProjectName}}
            {{form.ProjectLink}}
            {{form.ProjectDescription}}

            <button type="submit">ADD</button>
        </form>
                </div>
            </div>
{% endblock %}

taskmanager/main/templates/main/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'css/loginstyle.css'%}">
    <title>Login | DjangoDB</title>
</head>
<body>
    
    <div class="login-card">
        <h2>Login</h2>
        <h3>Enter your credentials</h3>

        <form class="login-form" method="post">
            {% csrf_token %}
            {{form.username}}
            {{form.password}}

            <a href="registration">Create new account.</a>
            <button type="submit">LOGIN</button>
        </form>
    </div>
</body>
</html>

taskmanager/main/templates/main/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'css/loginstyle.css'%}">
    <title>Register | DjangoDB</title>
</head>
<body>

    <div class="login-card">
        <h2>Registration</h2>
        <h3>Enter your credentials</h3>

        <form class="login-form" method="post">
            {% csrf_token %}
            {{form.username}}
            {{form.email}}
            {{form.password1}}
            {{form.password2}}
            <!--<input type="text" placeholder="GitHub project link">-->
    {% if form.errors %}
       {% for field in form %}
           {% for error in field.errors %}
              <a class="alert alert-danger" style="color: red";>

                      <strong>{{ error|escape }}</strong>
              </a>
           {% endfor %}
       {% endfor %}
    {% endif %}
            <a href="login">Already have account.</a>
            <button type="submit">REGISTER</button>
        </form>
    </div>
</body>
</html>

taskmanager/main/templates/main/settings.html
{% extends 'main/base.html' %}
{% load static %}

{% block main %}
<h1>Settings</h1>
            <div class="analyse">
                <div class="sales">

                </div>
            </div>
{% endblock %}

taskmanager/main/templates/main/test.html
{% extends 'main/base.html' %}
{% load static %}

{% block main %}
<a>Block MAIN</a>
{% endblock %}

taskmanager/main/templates/main/users.html
{% extends 'main/base.html' %}
{% load static %}

{% block main %}
<h1>Profile</h1>

            <div class="profileblock">
                <div class="profilesettings">
                    <div class="profilephoto">
                        <img src="{%static 'images/userunknown.jpg'%}">
                        <input type="hidden" name="UserAvatar" accept="image/*" id="id_UserAvatar">
                    </div>
                    <div class="profileusername">
                        {{request.user.username}}
                    </div>

                    <div class="login-card">
        <h3>Enter your credentials</h3>

        <form class="login-form" method="post">

            {% csrf_token %}
            {{form.UserAvatar}}
            {{form.Fullname}}
            {{form.UserGitLink}}
            {{form.UserGroup}}
            {{form.UserF}}

            <button type="submit">SUBMIT</button>
        </form>
                    </div>


                </div>
                <div class="profilepreview">
                    <div class="profilephoto">
                        <img src="{%static 'images/userunknown.jpg'%}">

                    </div>
                    <div class="profileusername">
                        {{request.user.username}}
                    </div>
                    <div class="profileinfo">
                        <div class="info-block">
                            <a class="halfvisible">
                                Fullname
                            </a>
                        </div>
                        <div class="profilename">
                            {{userdata.Fullname}}
                            </div>
                        <div class="info-block">
                                    <a class="halfvisible">
                                        GitHub link
                                    </a>
                                </div>
                        <div class="githubprofile">
                            <a href = {{userdata.UserGitLink}}>{{userdata.UserGitLink}}</a>
                        </div>
                         <div class="info-block">
                                    <a class="halfvisible">
                                        Group
                                    </a>
                                </div>
                        <div class="githubprofile">
                            {{userdata.UserGroup}}
                        </div>
<!--                        <img src="{%static 'images/nerd.png'%}">-->
                </div>
            </div>
            </div>
{% endblock %}